version: '3.8'  # Specify the version

services:
  web:
    build: ./secpred
    ports:
      - "8000:3000"

  backend:
    build: ./backend
    ports: 
      - "6000:3001"  
    

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"  

  db:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/var/lib/mongo

volumes:
  mongo_data: 